# MIDI Conversion Configuration
# Settings for converting drum stems to MIDI notes

# Audio Processing
audio:
  force_mono: true     # Convert stereo files to mono before analysis (recommended)
                       # Uses average of left/right channels

# Onset Detection Parameters (applies to all stems)
onset_detection:
  threshold: 0.01      # Onset strength threshold (0-1). Lower = more sensitive, catches quieter hits
  delta: 0.005         # Peak picking sensitivity. Lower = more sensitive
  wait: 1              # Minimum frames between peaks. 1 = ~11ms, allows fast repeated hits
  hop_length: 512      # Samples between frames. Affects time resolution

# Per-Stem Filtering Settings
# Each stem can have custom spectral filtering to reject artifacts and bleed

kick:
  # Kick drum (bass drum) settings
  midi_note: 36
  
  # Onset detection (overrides global onset_detection settings for kick)
  onset_threshold: null      # Use global setting (0.01) - kicks are loud and easy to detect
  onset_delta: null          # Use global setting (0.005)
  onset_wait: null           # Use global setting (1 frame ~11ms)
  
  # Spectral filtering uses FFT analysis to distinguish real kicks from artifacts
  # Real kick has energy in both fundamental (40-80Hz) and body/attack (80-150Hz)
  # Artifacts (snare bleed, clicks) have low energy in fundamental range
  
  geomean_threshold: 150.0   # Geometric mean of fundamental+body energy
                              # Real kicks: 200-800, Artifacts: 20-150
                              # Set to 150 to be conservative
                              # Increase to 200-250 for stricter filtering
  
  # Spectral ranges for analysis (Hz)
  fundamental_freq_min: 40   # Start of fundamental range (deep bass)
  fundamental_freq_max: 80   # End of fundamental range
  body_freq_min: 80          # Start of body/attack range
  body_freq_max: 150         # End of body/attack range
  attack_freq_min: 2000      # Start of beater attack range
  attack_freq_max: 6000      # End of beater attack range
  
snare:
  # Snare drum settings
  midi_note: 38
  
  # Onset detection (overrides global onset_detection settings for snare)
  onset_threshold: null      # Use global setting (0.01) - snares are loud and transient
  onset_delta: null          # Use global setting (0.005)
  onset_wait: null           # Use global setting (1 frame ~11ms)
  
  # Spectral filtering uses FFT analysis to distinguish real snare hits from artifacts
  # Real snare has energy in both body (150-400Hz) and wires (2-8kHz)
  # Artifacts (clicks, bleed) have low energy in both ranges
  
  geomean_threshold: 100.0   # Geometric mean of body+wire energy
                              # Real snares: 250-1200, Artifacts: 20-100
                              # Set to 100 to be conservative (catches all real snares)
                              # Increase to 150-200 for stricter filtering
  
  # Spectral ranges for analysis (Hz)
  low_freq_min: 40           # Start of low frequency range (kick bleed)
  low_freq_max: 150          # End of low frequency range
  body_freq_min: 150         # Start of snare body range
  body_freq_max: 400         # End of snare body range
  wire_freq_min: 2000        # Start of snare wire range
  wire_freq_max: 8000        # End of snare wire range

toms:
  # Tom drums settings
  midi_note: 45
  geomean_threshold: null  # Not used for toms yet
  
hihat:
  # Hi-hat settings
  midi_note: 42              # Closed hi-hat
  midi_note_open: 46         # Open hi-hat
  geomean_threshold: null    # Not used for hihat yet
  detect_open: true          # Try to detect open vs closed hi-hat
  decay_threshold: 0.65      # Threshold for open detection (higher = fewer open detections)
  
cymbals:
  # Crash/ride cymbal settings
  midi_note: 49
  
  # Onset detection (overrides global onset_detection settings for cymbals)
  # Cymbals need special handling due to long decay - prevent retriggering on sustain
  onset_threshold: 0.15      # Less sensitive than global (0.01) to avoid retriggering on decay
  onset_delta: 0.02          # Less sensitive peak picking (global: 0.005)
  onset_wait: 10             # Longer wait between peaks: 10 frames = ~115ms (global: 1 frame = ~11ms)
  
  # Spectral filtering
  geomean_threshold: 10      # Geometric mean of body (1-4kHz) + brilliance (4-10kHz) energy
                              # Real cymbals: 50-500, Artifacts: 5-20
  min_sustain_ms: 150        # Minimum sustain duration in milliseconds
                              # Real cymbal hits sustain longer than clicks/artifacts
                              # Typical values: 100-200ms

# MIDI Output Settings
midi:
  min_velocity: 40           # Minimum MIDI velocity (1-127)
  max_velocity: 127          # Maximum MIDI velocity
  default_tempo: 124.0       # Default tempo in BPM
  max_note_duration: 0.5     # Maximum duration for any note (seconds)
  
# Debug Output
debug:
  show_all_onsets: true      # Show detailed analysis of all detected onsets
  show_spectral_data: true   # Show spectral energy values (BodyE, WireE, etc)

# Threshold Learning Mode
# This workflow helps calibrate thresholds for your specific drum recordings
learning_mode:
  enabled: false                    # Enable learning mode
  export_all_detections: true       # Export ALL detected onsets (even rejected ones)
  rejected_velocity: 1               # Velocity for rejected hits (so you can see them)
  kept_velocity_normal: true         # Use normal velocity calculation for kept hits
  
  # In learning mode, use very sensitive detection to catch everything
  learning_onset_threshold: 0.05    # Very low threshold to catch all possible hits
  learning_delta: 0.002              # Very sensitive peak picking
  learning_wait: 1                   # Allow very close hits
  
  # Output locations for learning workflow
  learning_midi_suffix: "_learning"  # Suffix for learning MIDI files
  calibrated_config_output: "midiconfig_calibrated.yaml"  # Where to save learned config
