# MIDI Conversion Configuration
# Settings for converting drum stems to MIDI notes

# Audio Processing
audio:
  force_mono: true     # Convert stereo files to mono before analysis (recommended)
                       # Uses average of left/right channels
  silence_threshold: 0.001   # Amplitude threshold for silence detection (-60dB)
  min_segment_length: 512    # Minimum audio segment length for analysis (samples)
  
  # Peak amplitude detection
  peak_window_sec: 0.10      # Window size for peak detection (seconds)
  
  # Sustain detection (envelope analysis)
  sustain_window_sec: 0.2    # Window size for sustain analysis (seconds)
  envelope_threshold: 0.1    # Threshold for sustain detection (fraction of peak)
  envelope_smooth_kernel: 51 # Median filter kernel size for envelope smoothing (must be odd)
  
  # MIDI timing
  default_note_duration: 0.1     # Default duration for last note (seconds)
  very_short_duration: 0.01      # Very short note duration (beats) for MIDI output

# Onset Detection Parameters (applies to all stems)
onset_detection:
  threshold: 0.3       # Onset strength threshold (0-1). Lower = more sensitive, catches quieter hits
  delta: 0.01           # Peak picking sensitivity. Lower = more sensitive
  wait: 3              # Minimum frames between peaks. 1 = ~11ms, allows fast repeated hits
  hop_length: 512      # Samples between frames. Affects time resolution

# Per-Stem Filtering Settings
# Each stem can have custom spectral filtering to reject artifacts and bleed

kick:
  # Kick drum (bass drum) settings
  midi_note: 36
  
  # Onset detection (overrides global onset_detection settings for kick)
  onset_threshold: 0.1      # Use global setting (0.01) - kicks are loud and easy to detect
  onset_delta: 0.1          # Use global setting (0.005)
  onset_wait: 2             # Use global setting (1 frame ~11ms)
  timing_offset: -0.014      # Timing offset in seconds (compensates for backtracking being too early)
                            # Positive values shift MIDI events later
                            # Typical range: 0.020-0.050 seconds (20-50ms)
  
  # TWO-PASS FILTERING SYSTEM for kick drums
  # Pass 1: Spectral filtering (GeoMean threshold)
  # Pass 2: Statistical outlier detection (optional, catches snare bleed)
  
  # Pass 1: Spectral filtering uses FFT analysis to distinguish real kicks from artifacts
  # Real kick has energy in fundamental (40-80Hz), body (80-250Hz), and attack (1.5-5kHz)
  # Artifacts (snare bleed, clicks) have low energy in one or more ranges
  
  geomean_threshold: 70.0   # Geometric mean of fundamental+body+attack energy (3-way: cube root)
                              # Real kicks: 100-400, Artifacts: 10-80
                              # Set to 70 to be conservative
                              # Increase to 100-150 for stricter filtering
  
  # Spectral ranges for analysis (Hz)
  fundamental_freq_min: 40   # Start of fundamental range (deep bass)
  fundamental_freq_max: 80   # End of fundamental range
  body_freq_min: 80          # Start of body/attack range
  body_freq_max: 250         # End of body/attack range
  attack_freq_min: 1500      # Start of beater attack range
  attack_freq_max: 5000      # End of beater attack range
  
  # Statistical outlier filtering (optional second-pass filter)
  # Detects snare bleed by comparing FundE/BodyE ratio and total energy
  # against the median values across all detected kicks
  enable_statistical_filter: true    # Enable/disable statistical outlier detection
  statistical_badness_threshold: 0.3  # Badness score threshold (0-1)
                                      # Higher = more permissive (0.6-0.7 recommended)
                                      # Lower = stricter filtering (0.4-0.5 very strict)
  statistical_ratio_weight: 0.7       # Weight for FundE/BodyE ratio deviation (0-1)
  statistical_total_weight: 0.3       # Weight for total energy deviation (0-1)
  
snare:
  # Snare drum settings
  midi_note: 38
  
  # Onset detection (overrides global onset_detection settings for snare)
  onset_threshold: 0.2          # Use global setting (0.01) - snares are loud and transient
  onset_delta: null             # Use global setting (0.005)
  onset_wait: 2                 # Use global setting (1 frame ~11ms)
  timing_offset: -0.007         # Timing offset in seconds (0 = no offset)
  
  # Spectral filtering uses FFT analysis to distinguish real snare hits from artifacts
  # Real snare has energy in both body (150-400Hz) and wires (2-8kHz)
  # Artifacts (clicks, bleed) have low energy in both ranges
  
  geomean_threshold: 40.0   # Geometric mean of body+wire energy
                              # Real snares: 250-1200, Artifacts: 20-100
                              # Set to 100 to be conservative (catches all real snares)
                              # Increase to 150-200 for stricter filtering
  
  # Spectral ranges for analysis (Hz)
  low_freq_min: 40           # Start of low frequency range (kick bleed)
  low_freq_max: 150          # End of low frequency range
  body_freq_min: 150         # Start of snare body range
  body_freq_max: 400         # End of snare body range
  wire_freq_min: 2000        # Start of snare wire range
  wire_freq_max: 8000        # End of snare wire range

toms:
  # Tom drums settings
  midi_note_low: 45      # A1 - Low Tom
  midi_note_mid: 47      # B1 - Mid Tom  
  midi_note_high: 50     # D2 - High Tom
  
  # Onset detection (overrides global onset_detection settings for toms)
  onset_threshold: null      # Use global setting (0.01) - toms are loud and transient
  onset_delta: null          # Use global setting (0.005)
  onset_wait: null           # Use global setting (1 frame ~11ms)
  timing_offset: 0.0         # Timing offset in seconds (0 = no offset)
  
  # Pitch detection for automatic low/mid/high classification
  enable_pitch_detection: true   # Detect pitch and assign to low/mid/high tom notes
  pitch_method: 'yin'            # Pitch detection algorithm: 'yin' or 'pyin' (more robust but slower)
  min_pitch_hz: 60               # Minimum expected tom pitch (low floor tom ~60Hz)
  max_pitch_hz: 250              # Maximum expected tom pitch (high rack tom ~250Hz)
  
  # Spectral filtering (similar to kick/snare)
  geomean_threshold: 80.0        # Geometric mean of fundamental+body energy
                                  # Real toms: 150-600, Artifacts: 20-80
                                  # Set to 80 to be conservative
  
  # Spectral ranges for analysis (Hz)
  fundamental_freq_min: 60       # Start of fundamental range (deep toms)
  fundamental_freq_max: 150      # End of fundamental range
  body_freq_min: 150             # Start of body/attack range
  body_freq_max: 400             # End of body/attack range
  
hihat:
  # Hi-hat settings
  midi_note_closed: 42       # F#1 - Closed hi-hat
  midi_note_open: 46         # A#1 - Open hi-hat
  midi_note: 42              # Default (closed) for backward compatibility
  
  # Onset detection (overrides global onset_detection settings for hihat)
  # Hi-hats can have very fast repeated hits, similar to cymbals but shorter sustain
  onset_threshold: 0.1      # Moderate sensitivity (between global 0.01 and cymbals 0.15)
  onset_delta: 0.01          # Moderate peak picking
  onset_wait: 5              # 3 frames = ~35ms min spacing (allows 16th notes at fast tempos)
  timing_offset: -0.017      # Timing offset in seconds (0 = no offset)
  
  # Open/Closed detection
  detect_open: true          # Enable open vs closed hi-hat detection
  decay_threshold: 0.65      # Threshold for open detection (higher = fewer open detections)
  open_sustain_ms: 100       # Open hi-hat sustain threshold (ms): >=100ms = open (learned from optimization)
  open_geomean_min: 262.0    # Open hi-hat GeoMean threshold: >=262 = open (learned from optimization)
  min_sustain_ms: 25         # Minimum sustain for artifact filtering (handclaps ~20ms, real hihats >25ms)
  
  # Classification logic: Open = (GeoMean >= open_geomean_min) AND (SustainMs >= open_sustain_ms)
  # Closed = everything else that passes geomean_threshold
  
  # Spectral filtering
  geomean_threshold: 20.0    # Geometric mean of body (500-2kHz) + sizzle (6-12kHz) energy
                              # Real hi-hats: 100-400, Artifacts: 10-50
                              # Set to 50 to be conservative (OR condition with sustain)
  
  # Spectral ranges for analysis (Hz)
  body_freq_min: 500         # Start of body/attack range (hi-hats are bright)
  body_freq_max: 2000        # End of body range
  sizzle_freq_min: 6000      # Start of sizzle/shimmer range (key characteristic)
  sizzle_freq_max: 12000     # End of sizzle range
  
cymbals:
  # Crash/ride cymbal settings
  midi_note: 57              # GM: 49=Crash 1 (left), 57=Crash 2 (right)
  
  # Onset detection (overrides global onset_detection settings for cymbals)
  # Strategy: Low sensitivity to detect only strong initial hits, then use spectral
  # decay analysis to filter retriggering artifacts
  onset_threshold: 0.35      # High threshold - only detect strong crashes (reduced false positives)
  onset_delta: 0.1           # Higher delta for stricter peak picking
  onset_wait: 10             # 10 frames = ~115ms min spacing (allows rapid crashes)
  timing_offset: 0.0         # Timing offset in seconds (0 = no offset)
  
  # Sustain analysis and decay pattern detection
  sustain_window_sec: 0.2    # Window size for sustain analysis AND decay pattern analysis (seconds)
                              # Cymbals need longer window than default (0.2s) to measure full decay
                              # Used to analyze spectral energy decay pattern: onsets within this window
                              # are filtered if they occur during exponential decay (not independent hits)
  
  # Spectral filtering
  geomean_threshold: 100      # Geometric mean of body (1-4kHz) + brilliance (4-10kHz) energy
                              # Real cymbals: 50-500, Artifacts: 5-20
  min_sustain_ms: 150        # Minimum sustain duration in milliseconds
                              # Real cymbal hits sustain longer than clicks/artifacts
                              # Typical values: 100-200ms
  
  # MIDI note duration
  max_note_duration: 2.0     # Maximum MIDI note duration in seconds
                              # Uses actual sustain duration from envelope analysis
                              # Allows long cymbal crashes to ring out naturally

# MIDI Output Settings
midi:
  min_velocity: 80           # Minimum MIDI velocity (1-127)
  max_velocity: 110          # Maximum MIDI velocity
  default_tempo: 120.0       # Default tempo in BPM (matches DAW defaults like Logic Pro)
  max_note_duration: 0.5     # Maximum duration for any note (seconds)
  
# Debug Output
debug:
  show_all_onsets: true      # Show detailed analysis of all detected onsets
  show_spectral_data: true   # Show spectral energy values (BodyE, WireE, etc)

# Threshold Learning Mode
# This workflow helps calibrate thresholds for your specific drum recordings
learning_mode:
  enabled: false                    # Enable learning mode
  export_all_detections: true       # Export ALL detected onsets (even rejected ones)
  rejected_velocity: 1               # Velocity for rejected hits (so you can see them)
  kept_velocity_normal: true         # Use normal velocity calculation for kept hits
  
  # In learning mode, use very sensitive detection to catch everything
  learning_onset_threshold: 0.0001    # Very low threshold to catch all possible hits
  learning_delta: 0.002              # Very sensitive peak picking
  learning_wait: 1                   # Allow very close hits
  
  # Output locations for learning workflow
  learning_midi_suffix: "_learning"  # Suffix for learning MIDI files
  calibrated_config_output: "midiconfig_calibrated.yaml"  # Where to save learned config
