"""End-to-end test against the registered ground-truth project.

Validates that the live PGA pipeline produces sensible output for the
ground-truth song (2_funk_80_beat_4-4_4.aif) by reading the project's
existing analysis sidecar. This is a LOOSE smoke test — the sidecar
was generated by a previous pipeline run on this exact audio; the
test confirms the sidecar is well-formed and that the live pipeline
schema contract is satisfied.

The test does NOT re-run the pipeline (that would require demucs /
GPU). It validates the existing output. To regenerate, run:

    conda run -n drumtomidi python -m stems_to_midi_cli 4
    # or use the WebUI / separate.py first if stems are missing

Ground-truth MIDI comparison is intentionally tolerant (±50% per stem)
because (a) the PGA detector is more sensitive than the ground truth's
note-on/off MIDI, and (b) the per-event KEPT count is intentionally
smaller than the candidate count (per the prominence + decay_col_min
+ attack_rise filter chain). The asset's readme says "may not match
100%", so a strict count match is not the goal.
"""
from __future__ import annotations

from pathlib import Path


def test_ground_truth_project_registered(ground_truth_project_dir: Path):
    """The AIFF is registered as a real project under user_files/."""
    assert ground_truth_project_dir.exists(), (
        f"Ground-truth project directory not found: {ground_truth_project_dir}. "
        f"Run `python scripts/register_ground_truth_project.py` to register it."
    )
    assert ground_truth_project_dir.is_dir()
    # Standard project layout
    assert (ground_truth_project_dir / "midiconfig.yaml").exists()
    assert (ground_truth_project_dir / "midi").exists()
    assert (ground_truth_project_dir / "stems").exists()
    # Metadata
    metadata = ground_truth_project_dir / ".drumtomidi_project.json"
    assert metadata.exists(), "Project metadata file missing"


def test_ground_truth_sidecar_format(ground_truth_sidecar: dict):
    """The existing sidecar has the v3.0 shape (logic + events_pga per stem)."""
    assert ground_truth_sidecar.get("version") == "3.0", (
        f"Sidecar version mismatch: expected '3.0', got "
        f"{ground_truth_sidecar.get('version')!r}. Re-run the pipeline "
        f"to regenerate the sidecar (stems_to_midi_cli.py <project_num>)."
    )
    stems = ground_truth_sidecar.get("stems", {})
    assert isinstance(stems, dict)
    # Each processed stem should have events_pga (the canonical PGA
    # candidate list). We don't require all 5 stems to be present —
    # older runs may not have processed all of them. We do require the
    # structure to be valid when present.
    for stem_type, stem_data in stems.items():
        assert isinstance(stem_data, dict)
        # No events_spectral — removed in Phase 5
        assert "events_spectral" not in stem_data, (
            f"stems.{stem_type} still carries events_spectral "
            f"(removed in Phase 5); the sidecar is stale."
        )
        # events_pga should be a list
        pga = stem_data.get("events_pga", [])
        assert isinstance(pga, list)


def test_ground_truth_hihat_pga_nonzero(ground_truth_sidecar: dict):
    """Hihat (which is fully processed in the current project) has
    a non-trivial PGA candidate count. The ground-truth MIDI has
    359 hihat notes; the PGA detector is expected to find a
    larger candidate pool (typically 2-5x) before filters reduce
    it down to the final note count.
    """
    hihat = ground_truth_sidecar.get("stems", {}).get("hihat")
    if hihat is None:
        # Older run didn't process hihat — skip rather than fail.
        return
    pga = hihat.get("events_pga", [])
    assert len(pga) > 0, "Hihat PGA candidate pool is empty — pipeline is broken"


def test_ground_truth_midi_vs_pga_loose(ground_truth_sidecar: dict, ground_truth_midi_notes: dict):
    """Compare per-stem KEPT (PGA-filtered) count to ground-truth MIDI
    note count with ±50% tolerance.

    Loose by design — see module docstring. Toms has 0 ground-truth
    notes so we accept any small number for toms.
    """
    stems = ground_truth_sidecar.get("stems", {})
    for stem_type, gt_count in ground_truth_midi_notes.items():
        stem_data = stems.get(stem_type)
        if stem_data is None:
            continue
        # KEPT events (post-filter) for this stem
        kept = [e for e in stem_data.get("events_pga", []) if e.get("status") == "KEPT"]
        kept_count = len(kept)
        if gt_count == 0:
            # No ground truth — just assert the pipeline didn't hallucinate events.
            assert kept_count <= 10, (
                f"{stem_type}: ground truth has 0 notes but pipeline produced "
                f"{kept_count} KEPT events"
            )
        else:
            # Allow ±50% (loose per the asset's readme "may not match 100%")
            lo = int(gt_count * 0.5)
            hi = int(gt_count * 1.5) + 1
            assert lo <= kept_count <= hi, (
                f"{stem_type}: kept={kept_count} not within ±50% of "
                f"ground-truth MIDI count {gt_count} (range [{lo}, {hi}])"
            )
